# Site settings
title: WangZhen Blog
SEOTitle: WangZhen Blog
header-img: img/home-bg.jpg
email: youwangzhen@163.com
keyword: "王振, wanzghen Blog, 王振的博客, 传播, 博客, 个人网站, 互联网, 后台开发, 旅行，摄影"
url: "http://zhenwang.me"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'




# SNS settings
RSS: false
weibo_username:     ANT1299
github_username:    kailuncen
linkedin_username: wangzhen1413
#twitter_username:  huxpro
#facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: false                     # set to false if you want to use Comment without Sharing

# Netease setttings
netease_comment: true




# Analytics settings
# Baidu Analytics
ba_track_id: 5d5cae85adb9bb329878f7b4731e1972
# Google Analytics
ga_track_id: 'UA-101520487-1'            # Format: UA-xxxxxx-xx
ga_domain: kailuncen.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "美团点评后端工程师，技术爱好者。"
sidebar-avatar: /img/avatar-wangzhen.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0             # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "小土刀",
        href: "http://wdxtub.com/"
    },{
        title: "暗时间",
        href: "http://mindhacks.cn"
    },{
        title: "黄玄的博客",
        href: "http://huangxuan.me"
    },{
        title: "一肩月光",
        href: "http://zwb.io/"
    },{
        title: "初尘的博客",
        href: "https://perhapslove.github.io/"
    },{
        title: "Bruce Zhao's Blog",
        href: "http://brucezhaor.github.io/"
    },{
        title: "kailun blog",
        href: "http://kailuncen.me/"
    } ,{
        title: "王振的lofter",
        href: "http://wangzhenlofter.lofter.com/"
    }
]


